/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CliAuthRouteImport } from './routes/cli-auth'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ExtensionsExtensionIdRouteImport } from './routes/extensions.$extensionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CliAuthRoute = CliAuthRouteImport.update({
  id: '/cli-auth',
  path: '/cli-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtensionsExtensionIdRoute = ExtensionsExtensionIdRouteImport.update({
  id: '/extensions/$extensionId',
  path: '/extensions/$extensionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cli-auth': typeof CliAuthRoute
  '/settings': typeof SettingsRoute
  '/extensions/$extensionId': typeof ExtensionsExtensionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cli-auth': typeof CliAuthRoute
  '/settings': typeof SettingsRoute
  '/extensions/$extensionId': typeof ExtensionsExtensionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cli-auth': typeof CliAuthRoute
  '/settings': typeof SettingsRoute
  '/extensions/$extensionId': typeof ExtensionsExtensionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cli-auth' | '/settings' | '/extensions/$extensionId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cli-auth' | '/settings' | '/extensions/$extensionId'
  id: '__root__' | '/' | '/cli-auth' | '/settings' | '/extensions/$extensionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CliAuthRoute: typeof CliAuthRoute
  SettingsRoute: typeof SettingsRoute
  ExtensionsExtensionIdRoute: typeof ExtensionsExtensionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cli-auth': {
      id: '/cli-auth'
      path: '/cli-auth'
      fullPath: '/cli-auth'
      preLoaderRoute: typeof CliAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extensions/$extensionId': {
      id: '/extensions/$extensionId'
      path: '/extensions/$extensionId'
      fullPath: '/extensions/$extensionId'
      preLoaderRoute: typeof ExtensionsExtensionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CliAuthRoute: CliAuthRoute,
  SettingsRoute: SettingsRoute,
  ExtensionsExtensionIdRoute: ExtensionsExtensionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
