/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CliAuthRouteImport } from './routes/cli-auth'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ExtensionsExtensionIdRouteImport } from './routes/extensions.$extensionId'
import { Route as PurchaseSuccessRouteImport } from './routes/purchase.success'
import { Route as ExtensionsExtensionIdIndexRouteImport } from './routes/extensions.$extensionId.index'
import { Route as ExtensionsExtensionIdLicensingRouteImport } from './routes/extensions.$extensionId.licensing'
import { Route as ExtensionsExtensionIdPublishingRouteImport } from './routes/extensions.$extensionId.publishing'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CliAuthRoute = CliAuthRouteImport.update({
  id: '/cli-auth',
  path: '/cli-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtensionsExtensionIdRoute = ExtensionsExtensionIdRouteImport.update({
  id: '/extensions/$extensionId',
  path: '/extensions/$extensionId',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseSuccessRoute = PurchaseSuccessRouteImport.update({
  id: '/purchase/success',
  path: '/purchase/success',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtensionsExtensionIdIndexRoute =
  ExtensionsExtensionIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ExtensionsExtensionIdRoute,
  } as any)
const ExtensionsExtensionIdLicensingRoute =
  ExtensionsExtensionIdLicensingRouteImport.update({
    id: '/licensing',
    path: '/licensing',
    getParentRoute: () => ExtensionsExtensionIdRoute,
  } as any)
const ExtensionsExtensionIdPublishingRoute =
  ExtensionsExtensionIdPublishingRouteImport.update({
    id: '/publishing',
    path: '/publishing',
    getParentRoute: () => ExtensionsExtensionIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cli-auth': typeof CliAuthRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRoute
  '/settings': typeof SettingsRoute
  '/extensions/$extensionId': typeof ExtensionsExtensionIdRouteWithChildren
  '/purchase/success': typeof PurchaseSuccessRoute
  '/extensions/$extensionId/licensing': typeof ExtensionsExtensionIdLicensingRoute
  '/extensions/$extensionId/publishing': typeof ExtensionsExtensionIdPublishingRoute
  '/extensions/$extensionId/': typeof ExtensionsExtensionIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cli-auth': typeof CliAuthRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRoute
  '/settings': typeof SettingsRoute
  '/purchase/success': typeof PurchaseSuccessRoute
  '/extensions/$extensionId/licensing': typeof ExtensionsExtensionIdLicensingRoute
  '/extensions/$extensionId/publishing': typeof ExtensionsExtensionIdPublishingRoute
  '/extensions/$extensionId': typeof ExtensionsExtensionIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cli-auth': typeof CliAuthRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRoute
  '/settings': typeof SettingsRoute
  '/extensions/$extensionId': typeof ExtensionsExtensionIdRouteWithChildren
  '/purchase/success': typeof PurchaseSuccessRoute
  '/extensions/$extensionId/licensing': typeof ExtensionsExtensionIdLicensingRoute
  '/extensions/$extensionId/publishing': typeof ExtensionsExtensionIdPublishingRoute
  '/extensions/$extensionId/': typeof ExtensionsExtensionIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cli-auth'
    | '/login'
    | '/portal'
    | '/settings'
    | '/extensions/$extensionId'
    | '/purchase/success'
    | '/extensions/$extensionId/licensing'
    | '/extensions/$extensionId/publishing'
    | '/extensions/$extensionId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cli-auth'
    | '/login'
    | '/portal'
    | '/settings'
    | '/purchase/success'
    | '/extensions/$extensionId/licensing'
    | '/extensions/$extensionId/publishing'
    | '/extensions/$extensionId'
  id:
    | '__root__'
    | '/'
    | '/cli-auth'
    | '/login'
    | '/portal'
    | '/settings'
    | '/extensions/$extensionId'
    | '/purchase/success'
    | '/extensions/$extensionId/licensing'
    | '/extensions/$extensionId/publishing'
    | '/extensions/$extensionId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CliAuthRoute: typeof CliAuthRoute
  LoginRoute: typeof LoginRoute
  PortalRoute: typeof PortalRoute
  SettingsRoute: typeof SettingsRoute
  ExtensionsExtensionIdRoute: typeof ExtensionsExtensionIdRouteWithChildren
  PurchaseSuccessRoute: typeof PurchaseSuccessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cli-auth': {
      id: '/cli-auth'
      path: '/cli-auth'
      fullPath: '/cli-auth'
      preLoaderRoute: typeof CliAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extensions/$extensionId': {
      id: '/extensions/$extensionId'
      path: '/extensions/$extensionId'
      fullPath: '/extensions/$extensionId'
      preLoaderRoute: typeof ExtensionsExtensionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase/success': {
      id: '/purchase/success'
      path: '/purchase/success'
      fullPath: '/purchase/success'
      preLoaderRoute: typeof PurchaseSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extensions/$extensionId/': {
      id: '/extensions/$extensionId/'
      path: '/'
      fullPath: '/extensions/$extensionId/'
      preLoaderRoute: typeof ExtensionsExtensionIdIndexRouteImport
      parentRoute: typeof ExtensionsExtensionIdRoute
    }
    '/extensions/$extensionId/licensing': {
      id: '/extensions/$extensionId/licensing'
      path: '/licensing'
      fullPath: '/extensions/$extensionId/licensing'
      preLoaderRoute: typeof ExtensionsExtensionIdLicensingRouteImport
      parentRoute: typeof ExtensionsExtensionIdRoute
    }
    '/extensions/$extensionId/publishing': {
      id: '/extensions/$extensionId/publishing'
      path: '/publishing'
      fullPath: '/extensions/$extensionId/publishing'
      preLoaderRoute: typeof ExtensionsExtensionIdPublishingRouteImport
      parentRoute: typeof ExtensionsExtensionIdRoute
    }
  }
}

interface ExtensionsExtensionIdRouteChildren {
  ExtensionsExtensionIdLicensingRoute: typeof ExtensionsExtensionIdLicensingRoute
  ExtensionsExtensionIdPublishingRoute: typeof ExtensionsExtensionIdPublishingRoute
  ExtensionsExtensionIdIndexRoute: typeof ExtensionsExtensionIdIndexRoute
}

const ExtensionsExtensionIdRouteChildren: ExtensionsExtensionIdRouteChildren = {
  ExtensionsExtensionIdLicensingRoute: ExtensionsExtensionIdLicensingRoute,
  ExtensionsExtensionIdPublishingRoute: ExtensionsExtensionIdPublishingRoute,
  ExtensionsExtensionIdIndexRoute: ExtensionsExtensionIdIndexRoute,
}

const ExtensionsExtensionIdRouteWithChildren =
  ExtensionsExtensionIdRoute._addFileChildren(
    ExtensionsExtensionIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CliAuthRoute: CliAuthRoute,
  LoginRoute: LoginRoute,
  PortalRoute: PortalRoute,
  SettingsRoute: SettingsRoute,
  ExtensionsExtensionIdRoute: ExtensionsExtensionIdRouteWithChildren,
  PurchaseSuccessRoute: PurchaseSuccessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
